[package]
name = "vim-slides"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
notify = "4.0.17"
pad = "0.1.6"
